// app/layout.tsx
import './globals.css'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { ReactNode } from 'react'
import GridBG from './components/GridBG'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pabel Mahmud',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <GridBG />
        {children}
      </body>
    </html>
  )
}